"use client";

import { useEffect, useState } from "react";
import { useViewMode } from "@/lib/context/ViewModeContext";
import { 
  Check, 
  ArrowRight, 
  ArrowLeft, 
  Sparkles, 
  Compass, 
  RotateCcw, 
  Zap, 
  Package, 
  Leaf 
} from "lucide-react";

interface TourStepDef {
  stepIndex: number;
  title: string;
  targetId: string;
  lead: string;
  example?: string;
  bullets?: { icon: any; title: string; desc: string; color?: string }[];
  details?: string;
  callout?: string;
  disclaimer?: string;
}

// 1. Static Tour Step Definitions (Outside component to ensure stable references)
const TOUR_STEPS: TourStepDef[] = [
  {
    stepIndex: 1,
    title: "1. Describe Your Scenario",
    targetId: "mission-input-field",
    lead: "Start here. Tell TACTIX what you want to simulate using your own words.",
    example: "Try something like: \"Simulate a 5-hour scenario under heavy rain with limited resources.\"",
    details: "You don't need to fill in technical settings manually.",
  },
  {
    stepIndex: 2,
    title: "2. Review the Scenario",
    targetId: "scenario-review-card",
    lead: "TACTIX converts your description into structured simulation conditions.",
    bullets: [
      { icon: Sparkles, title: "Weather", desc: "Monsoon, gale, or normal", color: "#3B82F6" },
      { icon: Check, title: "Resources", desc: "Available fuel and assets", color: "#00D9A3" },
      { icon: Check, title: "Time Limit", desc: "Mission cutoff deadline", color: "#FFB020" },
      { icon: Compass, title: "Terrain Rule", desc: "Avoid slopes or water", color: "#8B6F47" },
    ],
    details: "Check these values before running the simulation. You can edit them if needed.",
  },
  {
    stepIndex: 3,
    title: "3. Run the Simulation",
    targetId: "run-simulation-btn",
    lead: "When the scenario looks right, run the simulation.",
    details: "TACTIX combines the scenario conditions with the simulated environment, constraints and routing engine to generate the results.",
  },
  {
    stepIndex: 4,
    title: "4. Explore the Simulated Environment",
    targetId: "map-section",
    lead: "This map shows the simulated environment and the alternatives generated by TACTIX.",
    details: "Use the map to understand roads, water, terrain and the simulated options.",
    callout: "Use Map Layers when you want to show or hide additional environmental information.",
  },
  {
    stepIndex: 5,
    title: "5. Compare Simulated Options",
    targetId: "coa-section",
    lead: "TACTIX generates different simulated alternatives so you can compare their trade-offs.",
    bullets: [
      { icon: Zap, title: "⚡ Option Alpha", desc: "Faster simulated option.", color: "#00D9A3" },
      { icon: Package, title: "📦 Option Bravo", desc: "Resource-efficient simulated option.", color: "#3B82F6" },
      { icon: Leaf, title: "🌿 Option Charlie", desc: "Lower environmental difficulty.", color: "#FFB020" },
    ],
    details: "Compare risk, duration, resources and validity to understand how they differ.",
    disclaimer: "These are simulated alternatives, not real-world operational instructions.",
  },
  {
    stepIndex: 6,
    title: "6. Understand the Risk",
    targetId: "risk-section",
    lead: "This section shows the simulated risk for the selected option.",
    details: "Risk is calculated from the simulation using factors such as weather, terrain, resources, information uncertainty, time and constraints.",
    callout: "Select [ Why? ] or [ Understand Risk ] to see why the result is different.",
  },
  {
    stepIndex: 7,
    title: "7. Test What-If Scenarios",
    targetId: "whatif-section",
    lead: "Want to see what happens when conditions change?",
    details: "Open What-If to change conditions such as weather, resources or available time and run the simulation again.",
    callout: "TACTIX shows the difference between the original and changed scenario.",
  },
];

const TOTAL_STEPS = 7;

export function GuidedTourModal() {
  const { isTourOpen, closeTour, tourStep, setTourStep } = useViewMode();
  
  const [targetRect, setTargetRect] = useState<{ top: number; left: number; width: number; height: number } | null>(null);
  const [popupPos, setPopupPos] = useState<{ top: number; left: number }>({ top: 120, left: 100 });
  const [showSkipConfirm, setShowSkipConfirm] = useState(false);

  const isStartScreen = tourStep === 0;
  const isFinalScreen = tourStep > TOTAL_STEPS;
  const currentStep = !isStartScreen && !isFinalScreen ? TOUR_STEPS[tourStep - 1] : null;

  // Single-pass position calculation on step change or window resize (Guaranteed zero infinite update loops)
  useEffect(() => {
    if (!isTourOpen || isStartScreen || isFinalScreen) {
      setTargetRect(null);
      return;
    }

    const stepDef = TOUR_STEPS[tourStep - 1];
    if (!stepDef) return;

    let targetElement = document.getElementById(stepDef.targetId);
    if (!targetElement) {
      if (stepDef.targetId === "whatif-section") {
        targetElement = document.getElementById("whatif-nav-btn") || document.getElementById("whatif-section");
      } else if (stepDef.targetId === "mission-input-field") {
        targetElement = document.getElementById("mission-input-card");
      }
    }

    if (targetElement) {
      try {
        targetElement.scrollIntoView({ behavior: "smooth", block: "center", inline: "nearest" });
      } catch (e) {
        // Fallback for environments where smooth scrolling is unsupported
      }

      const rect = targetElement.getBoundingClientRect();
      setTargetRect({
        top: rect.top,
        left: rect.left,
        width: rect.width,
        height: rect.height,
      });

      const popupWidth = Math.min(440, typeof window !== "undefined" ? window.innerWidth - 32 : 400);
      const popupHeight = 260;
      const margin = 16;

      let top = rect.bottom + margin;
      let left = Math.max(16, Math.min((typeof window !== "undefined" ? window.innerWidth : 1200) - popupWidth - 16, rect.left + (rect.width / 2) - (popupWidth / 2)));

      if (typeof window !== "undefined") {
        if (top + popupHeight > window.innerHeight && rect.top - popupHeight - margin > 60) {
          top = rect.top - popupHeight - margin;
        } else if (top + popupHeight > window.innerHeight) {
          top = Math.max(80, (window.innerHeight - popupHeight) / 2);
        }
      }

      setPopupPos({ top, left });
    } else {
      setTargetRect(null);
      setPopupPos({
        top: 140,
        left: Math.max(16, typeof window !== "undefined" ? (window.innerWidth - 440) / 2 : 100),
      });
    }
  }, [isTourOpen, tourStep, isStartScreen, isFinalScreen]);

  // Keyboard navigation (Esc, Arrow keys, Enter)
  useEffect(() => {
    if (!isTourOpen) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        if (showSkipConfirm) {
          setShowSkipConfirm(false);
        } else {
          setShowSkipConfirm(true);
        }
      } else if (e.key === "ArrowRight" || e.key === "Enter") {
        if (!showSkipConfirm) {
          if (isStartScreen) setTourStep(1);
          else if (isFinalScreen) closeTour();
          else setTourStep(tourStep + 1);
        }
      } else if (e.key === "ArrowLeft") {
        if (!showSkipConfirm && tourStep > 1 && !isFinalScreen) {
          setTourStep(tourStep - 1);
        }
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isTourOpen, tourStep, isStartScreen, isFinalScreen, showSkipConfirm, setTourStep, closeTour]);

  if (!isTourOpen) return null;

  const handleSkipClick = () => setShowSkipConfirm(true);
  const handleConfirmSkip = () => {
    setShowSkipConfirm(false);
    closeTour();
  };

  return (
    <div className="fixed inset-0 z-50 overflow-hidden font-mono select-none">
      
      {/* 1. Interactive Spotlight Cutout Mask */}
      <svg className="fixed inset-0 w-full h-full pointer-events-none z-10 transition-all duration-300">
        <defs>
          <mask id="tour-spotlight-mask">
            <rect x="0" y="0" width="100%" height="100%" fill="white" />
            {targetRect && !isStartScreen && !isFinalScreen && (
              <rect
                x={Math.max(0, targetRect.left - 8)}
                y={Math.max(0, targetRect.top - 8)}
                width={targetRect.width + 16}
                height={targetRect.height + 16}
                rx="10"
                fill="black"
              />
            )}
          </mask>
        </defs>

        <rect
          x="0"
          y="0"
          width="100%"
          height="100%"
          fill="rgba(5, 8, 12, 0.75)"
          mask="url(#tour-spotlight-mask)"
        />
      </svg>

      {/* Target Glowing Border Outline */}
      {targetRect && !isStartScreen && !isFinalScreen && (
        <div
          className="fixed pointer-events-none z-20 border-2 border-tactical-green rounded-xl shadow-[0_0_25px_rgba(0,217,163,0.35)] transition-all duration-300 ease-out animate-pulse"
          style={{
            top: `${Math.max(0, targetRect.top - 8)}px`,
            left: `${Math.max(0, targetRect.left - 8)}px`,
            width: `${targetRect.width + 16}px`,
            height: `${targetRect.height + 16}px`,
          }}
        />
      )}

      {/* 2. Skip Confirmation Modal */}
      {showSkipConfirm && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-[#131A24] border border-[#2A3441] rounded-panel p-5 shadow-2xl max-w-xs w-full space-y-4 text-xs animate-in zoom-in-95 duration-150">
            <div className="space-y-1">
              <h4 className="font-bold text-slate-100 uppercase text-sm">Skip the tour?</h4>
              <p className="text-slate-400 text-[11px] leading-relaxed">
                You can replay this walkthrough anytime by clicking <b>Help &rarr; Replay Guided Tour</b>.
              </p>
            </div>
            <div className="flex items-center justify-end space-x-2 pt-1 border-t border-[#2A3441]">
              <button
                onClick={() => setShowSkipConfirm(false)}
                className="px-3 py-1.5 rounded-btn bg-[#1A2330] text-slate-300 hover:text-white"
              >
                Continue Tour
              </button>
              <button
                onClick={handleConfirmSkip}
                className="px-3.5 py-1.5 rounded-btn bg-tactical-red/20 text-tactical-red border border-tactical-red/40 hover:bg-tactical-red hover:text-white font-bold"
              >
                Skip
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 3. Tour Start / Welcome Screen */}
      {isStartScreen && (
        <div className="fixed inset-0 z-30 flex items-center justify-center p-4">
          <div className="w-full max-w-lg bg-[#131A24] border border-tactical-green/50 rounded-panel p-6 sm:p-7 shadow-2xl space-y-5 animate-in zoom-in-95 duration-200">
            
            <div className="space-y-2 border-b border-[#2A3441] pb-3">
              <div className="inline-flex items-center space-x-2 px-2.5 py-0.5 rounded bg-tactical-green/10 text-tactical-green text-[10px] font-bold border border-tactical-green/30">
                <span className="w-1.5 h-1.5 rounded-full bg-tactical-green animate-pulse" />
                <span>INTERACTIVE WALKTHROUGH</span>
              </div>
              <h2 className="text-xl sm:text-2xl font-bold text-slate-100 tracking-tight">
                TACTIX <span className="text-tactical-green">AI</span>
              </h2>
              <p className="text-sm font-semibold text-slate-300">
                &ldquo;Let&apos;s take a quick tour.&rdquo;
              </p>
            </div>

            <div className="bg-[#0B0F14] p-3.5 rounded-btn border border-[#2A3441] text-xs text-slate-300 leading-relaxed space-y-2">
              <p>
                TACTIX helps you describe a simulated scenario, generate and compare simulated alternatives, understand risk, and test how changing conditions affects the results.
              </p>
              <p className="text-tactical-green font-semibold">
                Let&apos;s see how it works.
              </p>
            </div>

            <div className="flex items-center justify-between pt-1 border-t border-[#2A3441] text-xs">
              <button
                onClick={handleSkipClick}
                className="text-slate-400 hover:text-slate-200 transition-colors px-2 py-1"
              >
                Skip Tour
              </button>

              <button
                onClick={() => setTourStep(1)}
                className="flex items-center space-x-2 px-5 py-2.5 rounded-btn bg-tactical-green text-black font-bold hover:bg-tactical-green/90 shadow-lg shadow-tactical-green/10"
              >
                <span>Start Tour</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>

          </div>
        </div>
      )}

      {/* 4. Interactive Step Popup */}
      {!isStartScreen && !isFinalScreen && currentStep && (
        <div
          className="fixed z-30 w-[420px] max-w-[92vw] bg-[#131A24]/95 backdrop-blur border border-tactical-green/50 rounded-panel p-5 shadow-2xl space-y-3.5 transition-all duration-300 ease-out animate-in fade-in zoom-in-95"
          style={{
            top: `${popupPos.top}px`,
            left: `${popupPos.left}px`,
          }}
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b border-[#2A3441] pb-2">
            <h3 className="text-xs sm:text-sm font-bold text-slate-100 uppercase tracking-wide flex items-center space-x-1.5">
              <span className="w-2 h-2 rounded-full bg-tactical-green" />
              <span>{currentStep.title}</span>
            </h3>
            <span className="text-[11px] text-tactical-green font-bold bg-tactical-green/10 px-2 py-0.5 rounded border border-tactical-green/30">
              Step {currentStep.stepIndex} of {TOTAL_STEPS}
            </span>
          </div>

          {/* Content */}
          <div className="space-y-2 text-xs text-slate-200 leading-relaxed">
            <p className="text-slate-100 font-semibold">{currentStep.lead}</p>

            {currentStep.example && (
              <div className="bg-[#0B0F14] p-2.5 rounded border border-[#2A3441] text-tactical-green text-[11px]">
                {currentStep.example}
              </div>
            )}

            {currentStep.bullets && (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 pt-1 text-[11px]">
                {currentStep.bullets.map((b, idx) => (
                  <div key={idx} className="bg-[#0B0F14] p-1.5 px-2 rounded border border-[#2A3441] flex items-center space-x-1.5">
                    <span className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: b.color }} />
                    <span className="font-bold text-slate-200">{b.title}:</span>
                    <span className="text-slate-400 truncate">{b.desc}</span>
                  </div>
                ))}
              </div>
            )}

            {currentStep.details && (
              <p className="text-slate-300 text-[11px]">{currentStep.details}</p>
            )}

            {currentStep.callout && (
              <div className="bg-tactical-blue/10 border border-tactical-blue/30 p-2 rounded text-tactical-blue text-[11px]">
                💡 {currentStep.callout}
              </div>
            )}

            {currentStep.disclaimer && (
              <p className="text-[10px] text-tactical-muted italic pt-1 border-t border-[#2A3441]/50">
                {currentStep.disclaimer}
              </p>
            )}
          </div>

          {/* Actions */}
          <div className="flex items-center justify-between pt-2 border-t border-[#2A3441] text-xs">
            <button
              onClick={handleSkipClick}
              className="text-slate-400 hover:text-slate-200 transition-colors text-[11px]"
            >
              Skip Tour
            </button>

            <div className="flex items-center space-x-2">
              {tourStep > 1 && (
                <button
                  onClick={() => setTourStep(tourStep - 1)}
                  className="flex items-center space-x-1 px-3 py-1.5 rounded-btn bg-[#1A2330] border border-[#2A3441] text-slate-300 hover:text-white"
                >
                  <ArrowLeft className="w-3.5 h-3.5" />
                  <span>Back</span>
                </button>
              )}

              <button
                onClick={() => setTourStep(tourStep + 1)}
                className="flex items-center space-x-1.5 px-4 py-1.5 rounded-btn bg-tactical-green text-black font-bold hover:bg-tactical-green/90 shadow-sm"
              >
                <span>Next</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 5. Final Completion Screen */}
      {isFinalScreen && (
        <div className="fixed inset-0 z-30 flex items-center justify-center p-4">
          <div className="w-full max-w-md bg-[#131A24] border border-tactical-green/50 rounded-panel p-6 shadow-2xl space-y-5 text-center animate-in zoom-in-95 duration-200">
            
            <div className="space-y-1">
              <div className="w-10 h-10 rounded-full bg-tactical-green/20 text-tactical-green flex items-center justify-center mx-auto mb-2 border border-tactical-green/40">
                <Check className="w-5 h-5" />
              </div>
              <h3 className="text-xl font-bold text-slate-100 uppercase">You&apos;re Ready</h3>
              <p className="text-xs text-slate-400">That&apos;s the basic TACTIX workflow.</p>
            </div>

            <div className="bg-[#0B0F14] p-3.5 rounded-btn border border-[#2A3441] text-xs font-semibold text-slate-300 space-y-1">
              <div className="flex items-center justify-center space-x-1.5 text-tactical-green text-[11px]">
                <span>Describe</span>
                <span>&rarr;</span>
                <span>Review</span>
                <span>&rarr;</span>
                <span>Run</span>
                <span>&rarr;</span>
                <span>Compare</span>
                <span>&rarr;</span>
                <span>Understand</span>
                <span>&rarr;</span>
                <span>What-If</span>
              </div>
              <p className="text-[11px] text-slate-400 font-normal pt-1">
                Start with a scenario in your own words. TACTIX will guide you from there.
              </p>
            </div>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-2.5 pt-1">
              <button
                onClick={closeTour}
                className="w-full sm:w-auto px-6 py-2.5 rounded-btn bg-tactical-green text-black font-bold text-xs uppercase tracking-wider hover:bg-tactical-green/90 shadow-lg shadow-tactical-green/10"
              >
                Start Exploring
              </button>

              <button
                onClick={() => setTourStep(1)}
                className="w-full sm:w-auto flex items-center justify-center space-x-1.5 px-4 py-2.5 rounded-btn bg-[#1A2330] border border-[#2A3441] text-xs text-slate-300 hover:text-white"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Replay Tour</span>
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  );
}
